In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

In [2]:
df = pd.read_excel('Bookings-70000-Rows.xlsx')

In [12]:
df.head()

,date,time,booking_id,booking_status,customer_id,vehicle_type,pickup_location,drop_location,v_tat,c_tat,canceled_rides_by_customer,canceled_rides_by_driver,incomplete_rides,incomplete_rides_reason,booking_value,payment_method,ride_distance,driver_ratings,customer_rating,vehicle_images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...

In [8]:

engine = create_engine(
    "postgresql+psycopg2://postgres:2605@localhost:5432/postgres"
)

with engine.connect() as conn:
    conn.execution_options(isolation_level="AUTOCOMMIT").execute(
        text('CREATE DATABASE "OLA"')
    )

print("Database OLA created!")

Database OLA created!

In [9]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:2605@localhost:5432/OLA"
)

with engine.connect() as conn:
    print("Connected to OLA!")

Connected to OLA!

In [11]:
df.to_sql(
    "bookings",
    engine,
    if_exists="replace",
    index=False
)

201

In [3]:
df.describe()

,Date,V_TAT,C_TAT,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating
count,71201,44271.000000,44271.000000,71201.000000,71201.000000,44271.000000,44271.000000
mean,2024-07-15 23:33:26.898498,171.323620,84.955275,548.233901,14.206598,3.997994,3.997145
min,2024-07-01 00:00:00,35.000000,25.000000,100.000000,0.000000,3.000000,3.000000
25%,2024-07-08 11:40:00,98.000000,55.000000,242.000000,0.000000,3.500000,3.500000
50%,2024-07-15 22:56:00,168.000000,85.000000,385.000000,8.000000,4.000000,4.000000
75%,2024-07-23 12:14:00,238.000000,115.000000,622.000000,27.000000,4.500000,4.500000
max,2024-07-31 00:00:00,308.000000,145.000000,2999.000000,49.000000,5.000000,5.000000
std,NaN,80.682293,35.959016,535.399324,15.778237,0.577948,0.578574

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 71201 entries, 0 to 71200
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        71201 non-null  datetime64[us]
 1   Time                        71201 non-null  object
 2   Booking_ID                  71201 non-null  str
 3   Booking_Status              71201 non-null  str
 4   Customer_ID                 71201 non-null  str
 5   Vehicle_Type                71201 non-null  str
 6   Pickup_Location             71201 non-null  str
 7   Drop_Location               71201 non-null  str
 8   V_TAT                       44271 non-null  float64
 9   C_TAT                       44271 non-null  float64
 10  Canceled_Rides_by_Customer  7214 non-null   str
 11  Canceled_Rides_by_Driver    12728 non-null  str
 12  Incomplete_Rides            44271 non-null  str
 13  Incomplete_Rides_Reason     2685 non-null   str
 14  Booking_Value               71201 non-null  int64
 15  Payment_Method              44271 non-null  str
 16  Ride_Distance               71201 non-null  int64
 17  Driver_Ratings              44271 non-null  float64
 18  Customer_Rating             44271 non-null  float64
 19  Vehicle Images              71201 non-null  str
dtypes: datetime64[us](1), float64(4), int64(2), object(1), str(12)
memory usage: 10.9+ MB

In [5]:
df.columns

Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT',
       'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver',
       'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating',
       'Vehicle Images'],
      dtype='str')

In [ ]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [7]:
df.columns

Index(['date', 'time', 'booking_id', 'booking_status', 'customer_id',
       'vehicle_type', 'pickup_location', 'drop_location', 'v_tat', 'c_tat',
       'canceled_rides_by_customer', 'canceled_rides_by_driver',
       'incomplete_rides', 'incomplete_rides_reason', 'booking_value',
       'payment_method', 'ride_distance', 'driver_ratings', 'customer_rating',
       'vehicle_images'],
      dtype='str')